Bot commands#21
lsd-maddrive/qr_conveyor pull request #41
Opened 2024-05-04 21:38 UTC by mrGremlin2019

2024-05-07 18:08 UTC, serykhelena requested changes

2024-05-07 18:08 UTC, serykhelena commented on qr_conveyor/bot/handlers/command_handlers.py
> +session = Session()
Этот блок кода не используется

2024-05-07 18:08 UTC, serykhelena commented on qr_conveyor/bot/handlers/command_handlers.py
> +logging.basicConfig(level=logging.INFO, stream=sys.stdout)
Конфиг логгера указывается только в скриптах, не в исходниках

2024-05-07 18:08 UTC, serykhelena commented on qr_conveyor/bot/handlers/command_handlers.py
> +    product = DatabaseClient().get_product_by_id(product_id)
Не корректно используется класс-клиент. У тебя уже есть глобальный экземпляр, не нужно плодить новые инстансы

2024-05-07 18:08 UTC, serykhelena commented on qr_conveyor/database/client.py
>                  return status
Можно сделать return status вне условий, чтобы убрать дублирование

2024-05-07 18:08 UTC, serykhelena commented on scripts/run_bot.py
> +sys.path.append(str(project_root))
В проекте используется poetry, для него это не нужно
Используй poetry, а не pip

2024-05-07 18:08 UTC, serykhelena commented on scripts/run_bot.py
> +dp.include_router(command_handlers.router)
В глобальной области ничего не должно быть, перенеси в start_polling функцию

2024-05-08 19:21 UTC, serykhelena requested changes

2024-05-08 19:21 UTC, serykhelena commented on qr_conveyor/bot/handlers/command_handlers.py
> +# # Создаем сессию для работы с базой данных
Убрать закомментированый код

2024-05-08 19:21 UTC, serykhelena commented on qr_conveyor/bot/handlers/command_handlers.py
> +from sqlalchemy import create_engine
Убрать импорты, которые не используются

2024-05-08 19:21 UTC, serykhelena commented on qr_conveyor/bot/handlers/command_handlers.py
> +from qr_conveyor.database.client import DatabaseClient
Использовать относительные импорты, т.к. внутри исходников

2024-05-08 19:21 UTC, serykhelena commented on scripts/run_bot.py
> +load_dotenv()
Это тоже внутри функции start_polling

2024-05-10 10:51 UTC, serykhelena requested changes

2024-05-10 10:51 UTC, serykhelena commented on qr_conveyor/web_on_func.py
>  logging.basicConfig(level=logging.INFO)
Конфиг логгера не нужно указывать в исходниках, только во внешних скриптах

2024-05-10 10:51 UTC, serykhelena commented on qr_conveyor/web_on_func.py
> +from qr_conveyor.scan_qr import scan_qr_code
Относительные импорты внутри исходников

2024-05-10 20:01 UTC, serykhelena requested changes

2024-05-10 20:01 UTC, serykhelena commented on scripts/run_bot.py
> +from qr_conveyor.web_on_func import web_on
Убрать импорты, которые не используются scan_qr_code и web_on

2024-05-10 20:01 UTC, serykhelena commented on scripts/run_bot.py
> +from qr_conveyor.web_on_func import web_on
Убрать импорты, которые не используются scan_qr_code и web_on

2024-05-10 20:25 UTC, mrGremlin2019 commented on qr_conveyor/database/client.py
> +    import logging
случайно оказался там

2024-05-11 07:54 UTC, serykhelena requested changes

2024-05-11 07:54 UTC, serykhelena commented on qr_conveyor/database/models.py
> +from qr_conveyor.types import ProcesStatus, size_value# ProductSize
Убрать закомментированный код

2024-05-11 10:19 UTC, serykhelena requested changes

2024-05-11 10:19 UTC, serykhelena commented on qr_conveyor/database/models.py
> +from qr_conveyor.types import ProcesStatus
Относительные импорты внутри исходников

2024-05-11 10:46 UTC, serykhelena approved these changes

2024-05-11 10:46 UTC, merged